INSERT INTO SYSTEM.MOVIEDETAILS (URL,TITLE,DISCRIPTION,CATAGORY) VALUES
	 ('img/thor1.jpg','Thor: Love and Thunder','Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct','New Release'),
	 ('img/topgun.jpg','Top Gun: Maverick','After more than thirty years of service as one of the Navys top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.','New Release'),
	 ('img/batman.jpg','Batman','When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the citys hidden corruption and question his familys involvement','New Release'),
	 ('img/secretsofdum.jpg','Fantastic Beasts: The Secrets of Dumbledore','Professor Albus Dumbledore must assign Newt Scamander an his fellow partners as Grindelwald begins to lead an army to eliminate all Muggles.	','New Release'),
	 ('img/adamsproject.jpg','The Adam Project','After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self for a mission to save the future.','New Release'),
	 ('img/minions.jpg','Minions: The Rise of Gru','The untold story of one twelve-year-olds dream to become the worlds greatest supervillain.','New Release'),
	 ('img/batman.jpg','The Batman','When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the citys hidden corruption and question his familys involvement','TRENDING'),
	 ('img/spiderhead.jpg','Spiderhead','In the near future, convicts are offered the chance to volunteer as medical subjects to shorten their sentence. One such subject for a new drugcapable of generating feelings of love begins questioning the reality of his emotions.','TRENDING'),
	 ('img/northman.jpg','The Northman','From visionary director Robert Eggers comes The Northman, an action-filled epic that follows a young Viking prince on his quest to avenge his fathers murder','TRENDING'),
	 ('img/venom.jpg','Venom: Let There Be Carnage','Eddie Brock attempts to reignite his career by interviewing serial killer Cletus Kasady, who becomes the host of the symbiote Carnage and escapes prison after a failed execution','TRENDING');
INSERT INTO SYSTEM.MOVIEDETAILS (URL,TITLE,DISCRIPTION,CATAGORY) VALUES
	 ('img/rise.jpg','Rise','Based on the real life story about the family that produced the first trio of brothers to become NBA champions in the history of the league.','TRENDING'),
	 ('img/nowayhome.jpg','Spider-Man: No Way Home','With Spider-Man identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.','TRENDING'),
	 ('img/badguys.jpg','The Bad Guys','Several reformed yet misunderstood criminal animals attempt to become good, with some disastrous results along the way.','TRENDING'),
	 ('img/onepiecered.webp','One Piece Film: Red','The Straw Hats led by Luffy who simply came to enjoy Uta concert—the voice that the whole world has been waiting for is about to resound. The story begins with the shocking fact that she is Red-Haired Shanks','ANIME'),
	 ('img/demonslayer.webp','Demon Slayer: Mugen Train','After his family was brutally murdered and his sister turned into a demon, Tanjiro Kamados journey as a demon slayer began. Tanjiro and his      comrades embark on a new mission aboard the Mugen Train, on track to despair.','ANIME'),
	 ('img/attackontitans.jpg','Attack on Titan','After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction., on track to despair.','ANIME'),
	 ('img/Haikyu-Final-Poster.jpg','Haikyu','The movie covers Karasuno High finals match against Shiratorizawa Academy in the third season and includes new scenes showing what happened after the match.','ANIME'),
	 ('img/yourname.jpg','Your Name.','Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?','ANIME'),
	 ('img/spirited_away_xlg.jpg','Spirited Away','During her family move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.','ANIME'),
	 ('img/naruto.jpg','Naruto','Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village leader and strongest ninja.','ANIME');
INSERT INTO SYSTEM.MOVIEDETAILS (URL,TITLE,DISCRIPTION,CATAGORY) VALUES
	 ('img/jurrasic.jpg','Jurassic World Dominion','Jurassic World: Dominion takes place four years after Isla Nublar has been destroyed. This fragile balance will reshape the future and determine whether human beings are to remain the apex predators on a planet they now share with history`s most fearsome creatures.','New Release'),
	 ('img/venom.jpg','Venom:','Eddie Brock attempts to reignite his career by interviewing serial killer Cletus Kasady, who becomes the host of the symbiote Carnage and escapes prison after a failed execution','New Release');
